owner: dcorreia
suite:
  name: "suite_ngphylogeny"
  description: "NGPhylogeny Tools"
  type: repository_suite_definition
  categories:
    - "phylogeny"
  include_repositories:
    - name: "clustalo"
      owner: "dcorreia"
    - name: "mafft"
      owner: "fmareuil"
    - name: "muscle"
      owner: "fmareuil"
    - name: "noisy"
      owner: "fmareuil"
    - name: "gblocks"
      owner: "fmareuil"
    - name: "bmge"
      owner: "dcorreia"
    - name: "fastme"
      owner: "fmareuil"
    - name: "phyml_sms"
      owner: "dcorreia"
    - name: "phyml"
      owner: "fmareuil"
    - name: "newick_utilities"
      owner: "fmareuil"

