categories:
  - "phylogeny"
repositories:
  bmge:
    owner: dcorreia
    description: "BMGE (Block Mapping and Gathering with Entropy): Selection of phylogenetic informative regions"
    long_description: >
      "BMGE (Block Mapping and Gathering with Entropy)
      a new software for selection of phylogenetic informative regions from multiple sequence alignments"
    include:
      - bmge/bmge.xml

  clustalo:
    owner: dcorreia
    description: "Clustal Omega wrapper"
    long_description: >
      "Clustal Omega is a new multiple sequence alignment program that uses seeded guide trees and HMM profile-profile
      techniques to generate alignments. It offers a significant increase in scalability over previous versions.
      In addition, the quality of alignments is superior to previous versions, as measured by a range of popular
      benchmarks."
    include:
      - clustalo/clustalo.xml
      - clustalo/test-data/**

  goalign:
    owner: dcorreia
    description: "Goalign is a software to manipulate multiple alignments. It is implemented in Go language"
    include:
      - goalign/fasta_to_phylip.xml


  fasttree:
    owner: dcorreia
    description: "FastTree infers approximately-maximum-likelihood phylogenetic trees from alignments of nucleotide or protein sequences."
    include:
      - fasttree/fasttree.xml
      - fasttree/test-data/**

  fastme:
    owner: dcorreia
    description: "FastME Distance-based inference of phylogenetic trees"
    include:
      - fastme/fastme.xml
      - fastme/test-data/**

  gblocks:
    owner: fmareuil
    description: "Gblocks: automatic cleaning of alignments"
    long_description: >
      Gblocks eliminates poorly aligned positions and divergent regions of an alignment of DNA or protein sequences.
      Gblocks outputs several files to visualize the selected blocks. The use of a program such as Gblocks reduces
      the necessity of manually editing multiple alignments, makes the automation of phylogenetic analysis of large
      data sets feasible and, finally, facilitates the reproduction of the alignments and subsequent phylogenetic
      analysis by other researchers."
    include:
      - gblocks/gblocks.xml
      - gblocks/test-data/**

  mrbayes:
    owner: dcorreia
    description: "MrBayes MrBayes is a program for Bayesian inference and model choice across a wide range of phylogenetic and evolutionary models."
    include:
      - mrbayes/mrbayes.xml
      - mrbayes/test-data/**

  muscle:
    owner: fmareuil
    description: "MUSCLE: MUltiple Sequence Comparison by Log-Expectation is computer software for multiple sequence alignment of protein and nucleotide sequences."
    include:
      - muscle/muscle.xml
      - muscle/test-data/**

  newick_utilities:
    owner: fmareuil
    description: "Newick display from Newick utilities"
    include:
      - newick_utilities/nwdisplay.xml
      - newick_utilities/test-data/**

  noisy:
    owner: fmareuil
    description: "Noisy: identification of phylogenetically uninformative sites in a multiple sequence alignment"
    include:
      - noisy/noisy.xml
      - noisy/test-data/**

  phyml_sms:
    owner: dcorreia
    description: "PhyML with Smart Model Selection version 1.7"
    include:
      - phyml-sms/phyml_sms.xml
      - phyml-sms/test-data/**

  phyml:
    owner: fmareuil
    description: "Phylogeny software based on the maximum-likelihood"
    long_description: >
     "A simple, fast, and accurate algorithm to estimate large phylogenies by maximum likelihood"
    include:
      - phyml/phyml.xml
      - phyml/test-data/**